# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['thesubpackage']

package_data = \
{'': ['*']}

install_requires = \
['setuptools>=57.4.0,<58.0.0', 'typer>=0.3.2,<0.4.0']

setup_kwargs = {
    'name': 'thesubpackage',
    'version': '0.1.0',
    'description': '',
    'long_description': "Subpackage for testing poetry package dependency resolution using package install via git",
    'author': 'Sid',
    'author_email': "sid@example.com",
    'maintainer': "Sid",
    'maintainer_email': "sid@example.com",
    'url': 'https://github.com/sidmontu/subpackage',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.6,<4.0',
}


setup(**setup_kwargs)

# This setup.py was autogenerated using poetry.
